// src/core/ast.ts

//  Available Node Types
export type NodeType = 'OUTPUT_FRAG' | 'COLOR' | 'NOISE' | 'MULTIPLY';

//  Data Types for GLSL
export type GLSLType = 'float' | 'vec2' | 'vec3' | 'vec4';

//  The Port (Inputs and Outputs)
export interface NodePort {
    id: string;       // e.g., 'rgb', 'scale', 'result'
    type: GLSLType;   // e.g., 'vec3'
    value?: any;      
}

//  The Core Node
export interface ShaderNode {
    id: string;           // Unique identifier (UUID)
    type: NodeType;       // What kind of math/logic does this perform?
    inputs: NodePort[];   // Data required by this node
    outputs: NodePort[];  // Data generated by this node
    
    
}

// The Connection (The Wire)
export interface ShaderConnection {
    id: string;
    sourceNodeId: string; // Where does the wire start?
    sourcePortId: string; // Which exact output port?
    targetNodeId: string; // Where does the wire end?
    targetPortId: string; // Which exact input port?
}

//  The Complete Graph
export interface ShaderGraph {
    nodes: ShaderNode[];
    connections: ShaderConnection[];
}